title: "Martin Perfler"
description: "Snow • Mountains • Research • Code"
url: "https://machtlp.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"
plugins:
  - jekyll-include-cache
  - jekyll-sitemap


# Appearance



# Site Settings
locale                   : "en-CA"
title                    : "Martin Perfler"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Martin Perfler"
description              : "Portfolio"
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Author sidebar
author:
  name: "Martin <i>Machtl</i> Perfler"
  avatar: "/assets/img/machtl_profile.jpeg"   # optional
  bio: >-
    Snow crystals take a long path before falling onto our beautiful mountain landscapes
    and to be ready to draw a line in.<br>
    My path has led me from engineering and tightening screws on spacecraft to
    the question, <i>Is this the line I want to take?</i> Following my inner call for snow,
    I ended up here, somewhere between mountains and code...<br><br>
    + Snow and Avalanches <br>
    + Model development <br>
    + Mountains, Skiing, Paragliding 


  location: "Squamish, Canada"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:martin_perfler@sfu.ca"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/machtlp"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/machtl"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/ma.machtl/"


# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      toc: false

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include:
  - .htaccess
  - _pages

collections:
  projects:
    output: true
    permalink: /projects/:path/

